In [1]:
import pandas as pd
import requests
from zipfile import ZipFile
from io import BytesIO
import os
import json
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import seaborn as sns
import gzip
import shutil
import os
import json
import numpy as np

### Load data

In [ ]:
df_train = pd.read_csv("./MeetingBank-transcript/train.csv", delimiter=',')
df_train.head()

,meeting_id,source,type,reference,city
0,LongBeachCC_08092022_22-0922,Speaker 4: Thank you. And can we do the functi...,Agenda Item,Recommendation to increase appropriations in t...,LongBeachCC
1,LongBeachCC_08092022_22-0917,Speaker 4: We're going to hear all of the pres...,Public Hearing,Recommendation to conduct a Budget Hearing to ...,LongBeachCC
2,LongBeachCC_08092022_22-0946,Speaker 4: Thank you very much. We will. We're...,Ordinance,Recommendation to declare ordinance amending t...,LongBeachCC
3,LongBeachCC_08092022_22-0932,"Speaker 4: Great. Thank you. And, you know, we...",Resolution,Recommendation to adopt resolution approving t...,LongBeachCC
4,LongBeachCC_08092022_22-0926,Speaker 0: The motion is carried nine zero.\nS...,Agenda Item,Recommendation to refer to the Public Health a...,LongBeachCC

In [ ]:
df_test = pd.read_csv("./MeetingBank-transcript/test.csv", delimiter=',')
df_test.head()
# Count words for all source
df_test['word_count'] = df_test['source'].apply(lambda x: len(x.split()))

# Calculate mean and standard deviation
mean_word_count = df_test['word_count'].mean()
std_word_count = df_test['word_count'].std()

print(f"Mean word count: {mean_word_count}")
print(f"Standard deviation of word count: {std_word_count}")

Mean word count: 2775.7587006960557
Standard deviation of word count: 5610.365060635552

In [ ]:
import pandas as pd
path_csv_test = r".\dataset\test_data.csv"

df_test = pd.read_csv(path_csv_test)# Count words for all source
df_test['word_count'] = df_test['Description'].apply(lambda x: len(x.split()))

# Calculate mean and standard deviation
mean_word_count = df_test['word_count'].mean()
std_word_count = df_test['word_count'].std()

print(f"Mean word count: {mean_word_count}")
print(f"Standard deviation of word count: {std_word_count}")

Mean word count: 17.241655540720963
Standard deviation of word count: 10.897730720930138

In [ ]:
df_val = pd.read_csv("./MeetingBank-transcript/val.csv", delimiter=',')
df_val.head()

,meeting_id,source,type,reference,city
0,LongBeachCC_08092022_22-0949,Speaker 4: Thank you. And then we have our sec...,Contract,"Recommendation to authorize City Manager, or d...",LongBeachCC
1,LongBeachCC_08092022_22-0948,Speaker 0: Item 29 is a report from the City A...,Resolution,Recommendation to adopt resolution of the City...,LongBeachCC
2,LongBeachCC_08092022_22-0758,Speaker 4: Thank you. That concludes that item...,Ordinance,Recommendation to declare ordinance amending t...,LongBeachCC
3,LongBeachCC_08092022_22-0935,Speaker 0: Item 25 is a report from technology...,Contract,Recommendation to adopt Specifications No. ITB...,LongBeachCC
4,LongBeachCC_07192022_22-0828,Speaker 1: One Transfer Item 18 Communication ...,Agenda Item,Recommendation to increase appropriations in t...,LongBeachCC

### Setup LLM

In [ ]:
key = ""

In [ ]:
from langchain_openai import ChatOpenAI

os.environ["OPENAI_API_KEY"] = "{key}"

llm = ChatOpenAI(model_name="gpt-4o-mini")

### Test

In [6]:
# Test the llm.__call__ method with a sample prompt
test_prompt = "Quel est le résumé de la réunion suivante : Speaker 1: This is a test transcript for the meeting."
test_response = llm.invoke(test_prompt, max_tokens=100)
print(f"Test response: {test_response}")

Test response: content="Il semble que la transcription fournie soit très limitée et ne contient qu'une seule phrase de l'intervenant 1, sans plus de détails sur le contenu de la réunion. Pour un résumé de la réunion, il serait nécessaire d'avoir plus d'informations sur les sujets abordés, les discussions, les décisions prises et les actions à suivre. Si vous avez d'autres parties de la transcription ou des éléments supplémentaires, je serais heureux de vous aider à en faire un résumé." additional_kwargs={'refusal': None} response_metadata={'token_usage': {'completion_tokens': 96, 'prompt_tokens': 29, 'total_tokens': 125, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_00428b782a', 'finish_reason': 'stop', 'logprobs': None} id='run-a2b708c7-1df5-4095-bb01-200152dcd924-0' usage_metadata={'input_tokens': 29, 'output_tokens': 96, 'total_tokens': 125, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}

# Prompt

In [9]:
prompt_template = """
You are an assistant specialized in meeting text analysis. Your mission is to extract, from the following transcript, only the task CATEGORIES and their corresponding DESCRIPTIONS that must be completed as a result of the meeting.  

### Categories:  
1. **Document Writing** (e.g., writing reports, drafting bills, composing resolutions)  
2. **Meeting Planning** (e.g., scheduling meetings, organizing sessions, setting dates, preparing interviews)  
3. **Administrative Communication** (e.g., sending official emails, press releases, memos, text messages)  

### Instructions:  
- Extract **only** the tasks explicitly assigned or required for follow-up.  
- Ignore general discussions, suggestions, or ideas that do not translate into concrete actions.  
- Return the result in a structured, **parsable** JSON format.  

### **Expected Output Format:** 
# Leave task empty if no task is found 
```json
{
  "tasks": [
    {
      "category": "Document Writing",
      "description": "Draft the quarterly financial report."
    }, 
    {
      "category": "Meeting Planning",
      "description": "Schedule the next budget review meeting for Friday."
    },
    {
      "category": "Administrative Communication",
      "description": "Send out email reminders for the upcoming stakeholder meeting."
    }
  ]
}```
"""
context = "Here is the meeting transcript: {transcript}"

In [10]:
import json
import re

def parse_tasks(json_data):
    # Initialize the categories dictionary
    categories = {
        "Document Writing": "",
        "Meeting Planning": "",
        "Administrative Communication": ""
    }

    # Ensure input is a string
    if isinstance(json_data, str):
        # Remove Markdown-style code block markers (```json ... ```)
        json_data = re.sub(r"^```json|```$", "", json_data, flags=re.MULTILINE).strip()
        
        try:
            json_data = json.loads(json_data)  # Convert cleaned JSON string to dictionary
        except json.JSONDecodeError:
            print("Error: Invalid JSON format after cleaning")
            return categories  # Return empty categories instead of crashing

    # Iterate through the tasks and append descriptions to the corresponding category
    for task in json_data.get("tasks", []):
        category = task["category"]
        description = task["description"]
        
        if category in categories:
            categories[category] += " | " + description if categories[category] else description

    return categories

# Example usage with unmodified input
json_input = """
```json
{
  "tasks": [
    {
      "category": "Meeting Planning",
      "description": "Prepare for the consideration of Resolutions 348, 349, 350, and 351 on Monday, April 18."
    }
  ]
}"""


parsed_output = parse_tasks(json_input)

In [14]:
import ctypes

# Désactiver la mise en veille
ctypes.windll.kernel32.SetThreadExecutionState(0x80000002)  # ES_CONTINUOUS | ES_SYSTEM_REQUIRED

# Ton code ici...

# Réactiver la mise en veille à la fin
ctypes.windll.kernel32.SetThreadExecutionState(0x80000000)  # ES_CONTINUOUS

-2147483646

In [15]:
import logging

# Disable all logging
logging.disable(logging.CRITICAL)

In [16]:
import time
import threading
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from openai import RateLimitError
from tqdm import tqdm

def save_meeting_actions_to_csv(df, filename):
    results = pd.DataFrame(columns=[
        'meeting_id', 'Category_Document_Writing', 'Category_Meeting_Planning', 
        'Category_Administrative_Communication', 'Description_Document_Writing', 
        'Description_Meeting_Planning', 'Description_Administrative_Communication'
    ])

    # Rate limit management
    prompt_counter = 0
    start_time = time.time()
    prompt_counter_lock = threading.Lock()

    def process_row(i):
        """Processes a single row from the DataFrame."""
        nonlocal prompt_counter, start_time

        try:
            prompt = prompt_template + context.format(transcript=df['source'].iloc[i])
        except IndexError:
            print(f"Index {i} is out of bounds for the DataFrame.")
            return pd.DataFrame()
        except Exception as e:
            print(f"Error formatting prompt for row {i}: {e}")
            return pd.DataFrame()

        retries = 5
        while retries > 0:
            try:
                # Enforce rate limit: max 17 requests per minute
                with prompt_counter_lock:
                    if prompt_counter >= 17:
                        elapsed_time = time.time() - start_time
                        if elapsed_time < 60:
                            print(f"Rate limit reached. Sleeping for {60 - elapsed_time:.2f} seconds.")
                            time.sleep(60 - elapsed_time)  # Wait until next window
                        prompt_counter = 0
                        start_time = time.time()

                response = llm.invoke(prompt).content
                parsed_response = parse_tasks(response)

                new_row = pd.DataFrame({
                    'meeting_id': [df['meeting_id'].iloc[i]],
                    'Category_Document_Writing': [parsed_response['Document Writing'] != ""],
                    'Category_Meeting_Planning': [parsed_response['Meeting Planning'] != ""],
                    'Category_Administrative_Communication': [parsed_response['Administrative Communication'] != ""],
                    'Description_Document_Writing': [parsed_response['Document Writing']],
                    'Description_Meeting_Planning': [parsed_response['Meeting Planning']],
                    'Description_Administrative_Communication': [parsed_response['Administrative Communication']]
                })

                with prompt_counter_lock:
                    prompt_counter += 1

                return new_row

            except RateLimitError:
                retries -= 1
                if retries > 0:
                    print(f"Rate limit hit. Retrying in 2.43s... ({retries} retries left)")
                    time.sleep(2.43)
                else:
                    print(f"Max retries reached for row {i}. Skipping.")
                    return pd.DataFrame()

            except Exception as e:
                print(f"Unexpected error processing row {i}: {e}")
                return pd.DataFrame()

    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(process_row, i) for i in range(len(df))]

        batch_results = []
        for future in tqdm(as_completed(futures), total=len(futures), desc="Processing rows", ncols=100):
            result = future.result()
            if not result.empty:
                batch_results.append(result)

            if len(batch_results) >= 100:
                results = pd.concat([results] + batch_results, ignore_index=True)
                results.to_csv(filename, index=False)
                batch_results = []

        if batch_results:
            results = pd.concat([results] + batch_results, ignore_index=True)
            results.to_csv(filename, index=False)

# Example usage
save_meeting_actions_to_csv(df_val, "meeting_actions_val.csv")
save_meeting_actions_to_csv(df_test, "meeting_actions_test.csv")
save_meeting_actions_to_csv(df_train, "meeting_actions_train.csv")

Processing rows:   2%|▉                                            | 17/861 [00:10<12:35,  1.12it/s]

Rate limit reached. Sleeping for 49.18 seconds.

Processing rows:   4%|█▊                                           | 34/861 [01:02<16:13,  1.18s/it]

Rate limit reached. Sleeping for 56.75 seconds.

Processing rows:   6%|██▋                                          | 51/861 [02:05<21:11,  1.57s/it]

Rate limit reached. Sleeping for 54.70 seconds.

Processing rows:   8%|███▌                                         | 68/861 [03:06<20:44,  1.57s/it]

Rate limit reached. Sleeping for 53.70 seconds.

Processing rows:  10%|████▍                                        | 85/861 [04:03<17:13,  1.33s/it]

Rate limit reached. Sleeping for 56.32 seconds.

Processing rows:  12%|█████▏                                      | 102/861 [05:11<24:06,  1.91s/it]

Rate limit reached. Sleeping for 48.78 seconds.

Processing rows:  14%|██████                                      | 119/861 [06:08<20:40,  1.67s/it]

Rate limit reached. Sleeping for 50.96 seconds.

Processing rows:  16%|██████▉                                     | 136/861 [07:05<14:52,  1.23s/it]

Rate limit reached. Sleeping for 54.32 seconds.

Processing rows:  18%|███████▊                                    | 153/861 [08:04<14:13,  1.21s/it]

Rate limit reached. Sleeping for 55.23 seconds.

Processing rows:  20%|████████▋                                   | 170/861 [09:04<14:18,  1.24s/it]

Rate limit reached. Sleeping for 55.33 seconds.

Processing rows:  22%|█████████▌                                  | 187/861 [10:02<16:05,  1.43s/it]

Rate limit reached. Sleeping for 57.34 seconds.

Processing rows:  24%|██████████▍                                 | 204/861 [11:05<17:40,  1.61s/it]

Rate limit reached. Sleeping for 54.51 seconds.

Processing rows:  26%|███████████▏                                | 220/861 [12:04<15:37,  1.46s/it]

Rate limit reached. Sleeping for 54.94 seconds.

Processing rows:  28%|████████████                                | 237/861 [13:03<17:58,  1.73s/it]

Rate limit reached. Sleeping for 56.28 seconds.

Processing rows:  30%|████████████▉                               | 254/861 [14:03<14:36,  1.44s/it]

Rate limit reached. Sleeping for 56.34 seconds.

Processing rows:  31%|█████████████▊                              | 271/861 [15:03<13:58,  1.42s/it]

Rate limit reached. Sleeping for 56.16 seconds.

Processing rows:  34%|██████████████▊                             | 289/861 [16:03<10:47,  1.13s/it]

Rate limit reached. Sleeping for 56.58 seconds.

Processing rows:  36%|███████████████▋                            | 306/861 [17:02<15:30,  1.68s/it]

Rate limit reached. Sleeping for 57.56 seconds.

Processing rows:  37%|████████████████▍                           | 322/861 [18:02<17:56,  2.00s/it]

Rate limit reached. Sleeping for 56.98 seconds.

Processing rows:  39%|█████████████████▎                          | 339/861 [19:03<14:48,  1.70s/it]

Rate limit reached. Sleeping for 56.22 seconds.

Processing rows:  41%|██████████████████▏                         | 357/861 [20:02<10:59,  1.31s/it]

Rate limit reached. Sleeping for 57.02 seconds.

Processing rows:  43%|███████████████████                         | 373/861 [21:02<16:06,  1.98s/it]

Rate limit reached. Sleeping for 57.52 seconds.

Processing rows:  45%|███████████████████▉                        | 391/861 [22:03<10:47,  1.38s/it]

Rate limit reached. Sleeping for 56.82 seconds.

Processing rows:  47%|████████████████████▊                       | 408/861 [23:03<09:56,  1.32s/it]

Rate limit reached. Sleeping for 56.86 seconds.

Processing rows:  49%|█████████████████████▋                      | 424/861 [24:04<10:58,  1.51s/it]

Rate limit reached. Sleeping for 55.90 seconds.

Processing rows:  51%|██████████████████████▌                     | 442/861 [25:03<09:10,  1.31s/it]

Rate limit reached. Sleeping for 56.94 seconds.

Processing rows:  53%|███████████████████████▍                    | 458/861 [26:02<10:29,  1.56s/it]

Rate limit reached. Sleeping for 57.80 seconds.

Processing rows:  55%|████████████████████████▎                   | 476/861 [27:02<09:54,  1.54s/it]

Rate limit reached. Sleeping for 57.68 seconds.

Processing rows:  57%|█████████████████████████▏                  | 493/861 [28:02<09:17,  1.51s/it]

Rate limit reached. Sleeping for 57.50 seconds.

Processing rows:  59%|██████████████████████████                  | 509/861 [29:02<10:28,  1.79s/it]

Rate limit reached. Sleeping for 57.72 seconds.

Processing rows:  61%|██████████████████████████▉                 | 527/861 [30:02<07:04,  1.27s/it]

Rate limit reached. Sleeping for 57.20 seconds.

Processing rows:  63%|███████████████████████████▋                | 543/861 [31:02<07:05,  1.34s/it]

Rate limit reached. Sleeping for 57.51 seconds.

Processing rows:  65%|████████████████████████████▋               | 561/861 [32:02<07:24,  1.48s/it]

Rate limit reached. Sleeping for 57.29 seconds.

Processing rows:  67%|█████████████████████████████▌              | 578/861 [33:02<07:06,  1.51s/it]

Rate limit reached. Sleeping for 57.97 seconds.

Processing rows:  69%|██████████████████████████████▎             | 594/861 [34:02<06:02,  1.36s/it]

Rate limit reached. Sleeping for 57.12 seconds.

Processing rows:  71%|███████████████████████████████▎            | 612/861 [35:02<05:39,  1.36s/it]

Rate limit reached. Sleeping for 57.78 seconds.

Processing rows:  73%|████████████████████████████████▏           | 629/861 [36:02<05:48,  1.50s/it]

Rate limit reached. Sleeping for 57.26 seconds.

Processing rows:  75%|█████████████████████████████████           | 646/861 [37:02<05:16,  1.47s/it]

Rate limit reached. Sleeping for 57.67 seconds.

Processing rows:  77%|█████████████████████████████████▉          | 663/861 [38:03<04:23,  1.33s/it]

Rate limit reached. Sleeping for 56.67 seconds.

Processing rows:  79%|██████████████████████████████████▋         | 679/861 [39:02<04:17,  1.42s/it]

Rate limit reached. Sleeping for 57.25 seconds.

Processing rows:  81%|███████████████████████████████████▌        | 697/861 [40:03<04:33,  1.67s/it]

Rate limit reached. Sleeping for 56.91 seconds.

Processing rows:  83%|████████████████████████████████████▍       | 714/861 [41:03<04:03,  1.66s/it]

Rate limit reached. Sleeping for 56.71 seconds.

Processing rows:  85%|█████████████████████████████████████▎      | 731/861 [42:03<02:35,  1.20s/it]

Rate limit reached. Sleeping for 56.51 seconds.

Processing rows:  87%|██████████████████████████████████████▏     | 748/861 [43:03<02:17,  1.21s/it]

Rate limit reached. Sleeping for 56.38 seconds.

Processing rows:  89%|███████████████████████████████████████     | 764/861 [44:02<02:22,  1.47s/it]

Rate limit reached. Sleeping for 57.24 seconds.

Processing rows:  91%|███████████████████████████████████████▉    | 782/861 [45:05<01:59,  1.52s/it]

Rate limit reached. Sleeping for 54.39 seconds.

Processing rows:  93%|████████████████████████████████████████▊   | 799/861 [46:04<01:24,  1.37s/it]

Rate limit reached. Sleeping for 56.02 seconds.

Processing rows:  95%|█████████████████████████████████████████▋  | 816/861 [47:03<00:53,  1.19s/it]

Rate limit reached. Sleeping for 56.39 seconds.

Processing rows:  97%|██████████████████████████████████████████▌ | 833/861 [48:04<00:44,  1.57s/it]

Rate limit reached. Sleeping for 55.47 seconds.

Processing rows:  99%|███████████████████████████████████████████▍| 849/861 [49:02<00:21,  1.81s/it]

Rate limit reached. Sleeping for 57.46 seconds.

Processing rows: 100%|████████████████████████████████████████████| 861/861 [50:02<00:00,  3.49s/it]
Processing rows:   2%|▉                                            | 17/862 [00:06<03:08,  4.49it/s]

Rate limit reached. Sleeping for 53.79 seconds.

Processing rows:   4%|█▋                                           | 33/862 [01:03<20:00,  1.45s/it]

Rate limit reached. Sleeping for 56.12 seconds.

Processing rows:   6%|██▋                                          | 51/862 [02:02<16:04,  1.19s/it]

Rate limit reached. Sleeping for 57.17 seconds.

Processing rows:   8%|███▍                                         | 67/862 [03:03<20:23,  1.54s/it]

Rate limit reached. Sleeping for 56.44 seconds.

Processing rows:  10%|████▍                                        | 85/862 [04:03<18:51,  1.46s/it]

Rate limit reached. Sleeping for 56.88 seconds.

Processing rows:  12%|█████▏                                      | 102/862 [05:02<16:09,  1.28s/it]

Rate limit reached. Sleeping for 57.42 seconds.

Processing rows:  14%|██████                                      | 119/862 [06:02<14:50,  1.20s/it]

Rate limit reached. Sleeping for 57.13 seconds.

Processing rows:  16%|██████▉                                     | 136/862 [07:03<17:21,  1.43s/it]

Rate limit reached. Sleeping for 56.74 seconds.

Processing rows:  18%|███████▊                                    | 153/862 [08:04<17:26,  1.48s/it]

Rate limit reached. Sleeping for 55.43 seconds.

Processing rows:  20%|████████▋                                   | 170/862 [09:02<20:38,  1.79s/it]

Rate limit reached. Sleeping for 57.49 seconds.

Processing rows:  22%|█████████▌                                  | 187/862 [10:03<18:55,  1.68s/it]

Rate limit reached. Sleeping for 56.35 seconds.

Processing rows:  24%|██████████▍                                 | 204/862 [11:03<12:14,  1.12s/it]

Rate limit reached. Sleeping for 56.96 seconds.

Processing rows:  26%|███████████▎                                | 221/862 [12:03<13:43,  1.28s/it]

Rate limit reached. Sleeping for 56.85 seconds.

Processing rows:  28%|████████████▏                               | 238/862 [13:02<13:30,  1.30s/it]

Rate limit reached. Sleeping for 57.16 seconds.

Processing rows:  30%|█████████████                               | 255/862 [14:02<14:29,  1.43s/it]

Rate limit reached. Sleeping for 57.14 seconds.

Processing rows:  32%|█████████████▉                              | 272/862 [15:04<14:37,  1.49s/it]

Rate limit reached. Sleeping for 55.82 seconds.

Processing rows:  34%|██████████████▊                             | 289/862 [16:03<13:06,  1.37s/it]

Rate limit reached. Sleeping for 56.78 seconds.

Processing rows:  35%|███████████████▌                            | 306/862 [17:03<12:47,  1.38s/it]

Rate limit reached. Sleeping for 56.54 seconds.

Processing rows:  37%|████████████████▍                           | 323/862 [18:03<10:57,  1.22s/it]

Rate limit reached. Sleeping for 57.11 seconds.

Processing rows:  39%|█████████████████▎                          | 340/862 [19:02<09:51,  1.13s/it]

Rate limit reached. Sleeping for 57.36 seconds.

Processing rows:  41%|██████████████████▏                         | 357/862 [20:02<12:01,  1.43s/it]

Rate limit reached. Sleeping for 57.75 seconds.

Processing rows:  43%|███████████████████                         | 374/862 [21:02<11:31,  1.42s/it]

Rate limit reached. Sleeping for 57.26 seconds.

Processing rows:  45%|███████████████████▉                        | 391/862 [22:02<11:25,  1.46s/it]

Rate limit reached. Sleeping for 57.67 seconds.

Processing rows:  47%|████████████████████▊                       | 408/862 [23:03<12:54,  1.71s/it]

Rate limit reached. Sleeping for 57.09 seconds.

Processing rows:  49%|█████████████████████▋                      | 424/862 [24:01<12:16,  1.68s/it]

Rate limit reached. Sleeping for 58.22 seconds.

Processing rows:  51%|██████████████████████▌                     | 441/862 [25:03<12:59,  1.85s/it]

Rate limit reached. Sleeping for 56.78 seconds.

Processing rows:  53%|███████████████████████▍                    | 459/862 [26:02<07:09,  1.06s/it]

Rate limit reached. Sleeping for 57.50 seconds.

Processing rows:  55%|████████████████████████▏                   | 475/862 [27:02<09:25,  1.46s/it]

Rate limit reached. Sleeping for 57.66 seconds.

Processing rows:  57%|█████████████████████████▏                  | 493/862 [28:02<07:52,  1.28s/it]

Rate limit reached. Sleeping for 57.49 seconds.

Processing rows:  59%|█████████████████████████▉                  | 509/862 [29:03<10:18,  1.75s/it]

Rate limit reached. Sleeping for 56.99 seconds.

Processing rows:  61%|██████████████████████████▉                 | 527/862 [30:02<09:26,  1.69s/it]

Rate limit reached. Sleeping for 57.32 seconds.

Processing rows:  63%|███████████████████████████▊                | 544/862 [31:02<07:04,  1.34s/it]

Rate limit reached. Sleeping for 57.53 seconds.

Processing rows:  65%|████████████████████████████▋               | 561/862 [32:02<08:42,  1.74s/it]

Rate limit reached. Sleeping for 58.15 seconds.

Processing rows:  67%|█████████████████████████████▌              | 578/862 [33:02<07:55,  1.68s/it]

Rate limit reached. Sleeping for 57.85 seconds.

Processing rows:  69%|██████████████████████████████▎             | 594/862 [34:03<07:59,  1.79s/it]

Rate limit reached. Sleeping for 56.57 seconds.

Processing rows:  71%|███████████████████████████████▏            | 612/862 [35:03<05:26,  1.31s/it]

Rate limit reached. Sleeping for 56.90 seconds.

Processing rows:  73%|████████████████████████████████            | 629/862 [36:04<04:51,  1.25s/it]

Rate limit reached. Sleeping for 56.15 seconds.

Processing rows:  75%|████████████████████████████████▉           | 645/862 [37:04<06:40,  1.84s/it]

Rate limit reached. Sleeping for 55.76 seconds.

Processing rows:  77%|█████████████████████████████████▊          | 663/862 [38:03<04:34,  1.38s/it]

Rate limit reached. Sleeping for 56.49 seconds.

Processing rows:  79%|██████████████████████████████████▋         | 680/862 [39:03<03:17,  1.09s/it]

Rate limit reached. Sleeping for 57.22 seconds.

Processing rows:  81%|███████████████████████████████████▌        | 696/862 [40:03<04:51,  1.76s/it]

Rate limit reached. Sleeping for 56.88 seconds.

Processing rows:  83%|████████████████████████████████████▍       | 714/862 [41:03<03:26,  1.39s/it]

Rate limit reached. Sleeping for 57.02 seconds.

Processing rows:  85%|█████████████████████████████████████▎      | 731/862 [42:03<02:35,  1.19s/it]

Rate limit reached. Sleeping for 56.57 seconds.

Processing rows:  87%|██████████████████████████████████████      | 746/862 [43:03<03:32,  1.83s/it]

Rate limit reached. Sleeping for 57.15 seconds.

Processing rows:  89%|██████████████████████████████████████▉     | 764/862 [44:03<02:14,  1.37s/it]

Rate limit reached. Sleeping for 57.28 seconds.

Processing rows:  91%|███████████████████████████████████████▉    | 782/862 [45:03<01:45,  1.32s/it]

Rate limit reached. Sleeping for 56.69 seconds.

Processing rows:  93%|████████████████████████████████████████▊   | 799/862 [46:03<01:25,  1.35s/it]

Rate limit reached. Sleeping for 56.61 seconds.

Processing rows:  95%|█████████████████████████████████████████▋  | 816/862 [47:03<00:56,  1.23s/it]

Rate limit reached. Sleeping for 56.47 seconds.

Processing rows:  97%|██████████████████████████████████████████▌ | 833/862 [48:03<00:32,  1.12s/it]

Rate limit reached. Sleeping for 56.50 seconds.

Processing rows:  99%|███████████████████████████████████████████▍| 850/862 [49:02<00:13,  1.16s/it]

Rate limit reached. Sleeping for 57.67 seconds.

Processing rows: 100%|████████████████████████████████████████████| 862/862 [50:02<00:00,  3.48s/it]
Processing rows:   0%|▏                                           | 16/5169 [00:04<15:37,  5.49it/s]

Rate limit reached. Sleeping for 55.50 seconds.

Processing rows:   1%|▎                                         | 34/5169 [01:01<1:34:06,  1.10s/it]

Rate limit reached. Sleeping for 57.99 seconds.

Processing rows:   1%|▍                                         | 51/5169 [02:04<2:10:11,  1.53s/it]

Rate limit reached. Sleeping for 55.65 seconds.

Processing rows:   1%|▌                                         | 68/5169 [03:02<1:59:06,  1.40s/it]

Rate limit reached. Sleeping for 56.95 seconds.

Processing rows:   2%|▋                                         | 85/5169 [04:02<2:08:49,  1.52s/it]

Rate limit reached. Sleeping for 57.31 seconds.

Processing rows:   2%|▊                                        | 102/5169 [05:03<1:32:29,  1.10s/it]

Rate limit reached. Sleeping for 56.86 seconds.

Processing rows:   2%|▉                                        | 119/5169 [06:03<2:15:54,  1.61s/it]

Rate limit reached. Sleeping for 56.14 seconds.

Processing rows:   3%|█                                        | 135/5169 [07:01<2:06:43,  1.51s/it]

Rate limit reached. Sleeping for 57.85 seconds.

Processing rows:   3%|█▏                                       | 153/5169 [08:04<1:40:35,  1.20s/it]

Rate limit reached. Sleeping for 55.88 seconds.

Processing rows:   3%|█▎                                       | 170/5169 [09:01<2:18:16,  1.66s/it]

Rate limit reached. Sleeping for 58.07 seconds.

Processing rows:   4%|█▍                                       | 186/5169 [10:02<2:28:25,  1.79s/it]

Rate limit reached. Sleeping for 57.26 seconds.

Processing rows:   4%|█▌                                       | 204/5169 [11:03<1:50:13,  1.33s/it]

Rate limit reached. Sleeping for 56.90 seconds.

Processing rows:   4%|█▋                                       | 220/5169 [12:02<2:17:30,  1.67s/it]

Rate limit reached. Sleeping for 57.21 seconds.

Processing rows:   5%|█▉                                       | 238/5169 [13:03<1:55:22,  1.40s/it]

Rate limit reached. Sleeping for 56.38 seconds.

Processing rows:   5%|██                                       | 255/5169 [14:03<1:51:06,  1.36s/it]

Rate limit reached. Sleeping for 56.65 seconds.

Processing rows:   5%|██▏                                      | 271/5169 [15:02<1:53:07,  1.39s/it]

Rate limit reached. Sleeping for 57.27 seconds.

Processing rows:   6%|██▎                                      | 288/5169 [16:02<2:07:41,  1.57s/it]

Rate limit reached. Sleeping for 57.31 seconds.

Processing rows:   6%|██▍                                      | 306/5169 [17:02<2:05:28,  1.55s/it]

Rate limit reached. Sleeping for 57.31 seconds.

Processing rows:   6%|██▌                                      | 323/5169 [18:02<1:54:20,  1.42s/it]

Rate limit reached. Sleeping for 57.69 seconds.

Processing rows:   7%|██▋                                      | 340/5169 [19:02<1:52:30,  1.40s/it]

Rate limit reached. Sleeping for 57.19 seconds.

Processing rows:   7%|██▊                                      | 356/5169 [20:02<2:18:16,  1.72s/it]

Rate limit reached. Sleeping for 57.72 seconds.

Processing rows:   7%|██▉                                      | 373/5169 [21:02<2:01:07,  1.52s/it]

Rate limit reached. Sleeping for 57.49 seconds.

Processing rows:   8%|███                                      | 391/5169 [22:02<1:57:39,  1.48s/it]

Rate limit reached. Sleeping for 57.66 seconds.

Processing rows:   8%|███▏                                     | 407/5169 [23:02<1:51:52,  1.41s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:   8%|███▎                                     | 424/5169 [24:01<1:47:08,  1.35s/it]

Rate limit reached. Sleeping for 58.06 seconds.

Processing rows:   9%|███▌                                     | 442/5169 [25:02<1:37:27,  1.24s/it]

Rate limit reached. Sleeping for 57.93 seconds.

Processing rows:   9%|███▋                                     | 459/5169 [26:01<1:39:43,  1.27s/it]

Rate limit reached. Sleeping for 58.43 seconds.

Processing rows:   9%|███▊                                     | 475/5169 [27:02<1:48:03,  1.38s/it]

Rate limit reached. Sleeping for 57.12 seconds.

Processing rows:  10%|███▉                                     | 492/5169 [28:02<2:09:11,  1.66s/it]

Rate limit reached. Sleeping for 57.20 seconds.

Processing rows:  10%|████                                     | 510/5169 [29:02<1:36:59,  1.25s/it]

Rate limit reached. Sleeping for 57.12 seconds.

Processing rows:  10%|████▏                                    | 527/5169 [30:02<1:50:18,  1.43s/it]

Rate limit reached. Sleeping for 57.36 seconds.

Processing rows:  11%|████▎                                    | 544/5169 [31:02<1:45:45,  1.37s/it]

Rate limit reached. Sleeping for 57.28 seconds.

Processing rows:  11%|████▍                                    | 561/5169 [32:03<1:37:37,  1.27s/it]

Rate limit reached. Sleeping for 56.91 seconds.

Processing rows:  11%|████▌                                    | 578/5169 [33:03<1:41:43,  1.33s/it]

Rate limit reached. Sleeping for 56.52 seconds.

Processing rows:  12%|████▋                                    | 595/5169 [34:03<1:42:59,  1.35s/it]

Rate limit reached. Sleeping for 56.49 seconds.

Processing rows:  12%|████▊                                    | 611/5169 [35:02<2:03:15,  1.62s/it]

Rate limit reached. Sleeping for 57.76 seconds.

Processing rows:  12%|████▉                                    | 628/5169 [36:02<2:01:01,  1.60s/it]

Rate limit reached. Sleeping for 57.15 seconds.

Processing rows:  12%|█████                                    | 646/5169 [37:04<1:26:43,  1.15s/it]

Rate limit reached. Sleeping for 55.62 seconds.

Processing rows:  13%|█████▎                                   | 663/5169 [38:03<1:54:25,  1.52s/it]

Rate limit reached. Sleeping for 56.77 seconds.

Processing rows:  13%|█████▍                                   | 680/5169 [39:04<1:32:44,  1.24s/it]

Rate limit reached. Sleeping for 55.89 seconds.

Processing rows:  13%|█████▌                                   | 697/5169 [40:04<1:41:17,  1.36s/it]

Rate limit reached. Sleeping for 55.79 seconds.

Processing rows:  14%|█████▋                                   | 714/5169 [41:04<1:26:12,  1.16s/it]

Rate limit reached. Sleeping for 55.27 seconds.

Processing rows:  14%|█████▊                                   | 730/5169 [42:03<2:13:02,  1.80s/it]

Rate limit reached. Sleeping for 56.59 seconds.

Processing rows:  14%|█████▉                                   | 748/5169 [43:03<1:56:43,  1.58s/it]

Rate limit reached. Sleeping for 56.27 seconds.

Processing rows:  15%|██████                                   | 764/5169 [44:02<2:02:43,  1.67s/it]

Rate limit reached. Sleeping for 57.57 seconds.

Processing rows:  15%|██████▏                                  | 782/5169 [45:03<1:35:15,  1.30s/it]

Rate limit reached. Sleeping for 56.58 seconds.

Processing rows:  15%|██████▎                                  | 799/5169 [46:03<1:42:21,  1.41s/it]

Rate limit reached. Sleeping for 56.40 seconds.

Processing rows:  16%|██████▍                                  | 814/5169 [47:03<2:07:20,  1.75s/it]

Rate limit reached. Sleeping for 56.73 seconds.

Processing rows:  16%|██████▌                                  | 832/5169 [48:02<1:57:13,  1.62s/it]

Rate limit reached. Sleeping for 57.46 seconds.

Processing rows:  16%|██████▋                                  | 849/5169 [49:03<1:57:21,  1.63s/it]

Rate limit reached. Sleeping for 56.91 seconds.

Processing rows:  17%|██████▉                                  | 867/5169 [50:04<1:42:22,  1.43s/it]

Rate limit reached. Sleeping for 56.13 seconds.

Processing rows:  17%|███████                                  | 884/5169 [51:03<1:45:22,  1.48s/it]

Rate limit reached. Sleeping for 56.89 seconds.

Processing rows:  17%|███████▏                                 | 900/5169 [52:03<1:56:05,  1.63s/it]

Rate limit reached. Sleeping for 56.84 seconds.

Processing rows:  18%|███████▎                                 | 918/5169 [53:03<1:22:31,  1.16s/it]

Rate limit reached. Sleeping for 56.64 seconds.

Processing rows:  18%|███████▍                                 | 934/5169 [54:05<2:17:45,  1.95s/it]

Rate limit reached. Sleeping for 55.15 seconds.

Processing rows:  18%|███████▌                                 | 952/5169 [55:04<1:26:44,  1.23s/it]

Rate limit reached. Sleeping for 55.80 seconds.

Processing rows:  19%|███████▋                                 | 969/5169 [56:03<1:24:39,  1.21s/it]

Rate limit reached. Sleeping for 56.88 seconds.

Processing rows:  19%|███████▊                                 | 985/5169 [57:04<1:43:48,  1.49s/it]

Rate limit reached. Sleeping for 55.51 seconds.

Processing rows:  19%|███████▊                                | 1003/5169 [58:03<1:17:48,  1.12s/it]

Rate limit reached. Sleeping for 56.69 seconds.

Processing rows:  20%|███████▉                                | 1020/5169 [59:03<1:31:11,  1.32s/it]

Rate limit reached. Sleeping for 56.50 seconds.

Processing rows:  20%|███████▌                              | 1037/5169 [1:00:03<1:40:28,  1.46s/it]

Rate limit reached. Sleeping for 56.62 seconds.

Processing rows:  20%|███████▋                              | 1054/5169 [1:01:03<1:25:00,  1.24s/it]

Rate limit reached. Sleeping for 57.04 seconds.

Processing rows:  21%|███████▊                              | 1071/5169 [1:02:04<1:28:38,  1.30s/it]

Rate limit reached. Sleeping for 55.56 seconds.

Processing rows:  21%|███████▉                              | 1088/5169 [1:03:03<1:35:26,  1.40s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  21%|████████                              | 1105/5169 [1:04:03<2:03:05,  1.82s/it]

Rate limit reached. Sleeping for 57.08 seconds.

Processing rows:  22%|████████▏                             | 1122/5169 [1:05:04<1:42:47,  1.52s/it]

Rate limit reached. Sleeping for 56.16 seconds.

Processing rows:  22%|████████▎                             | 1139/5169 [1:06:04<1:32:29,  1.38s/it]

Rate limit reached. Sleeping for 56.30 seconds.

Processing rows:  22%|████████▍                             | 1156/5169 [1:07:03<1:49:03,  1.63s/it]

Rate limit reached. Sleeping for 56.49 seconds.

Processing rows:  23%|████████▌                             | 1173/5169 [1:08:04<1:28:02,  1.32s/it]

Rate limit reached. Sleeping for 56.27 seconds.

Processing rows:  23%|████████▋                             | 1190/5169 [1:09:04<1:43:18,  1.56s/it]

Rate limit reached. Sleeping for 56.15 seconds.

Processing rows:  23%|████████▊                             | 1207/5169 [1:10:04<1:48:45,  1.65s/it]

Rate limit reached. Sleeping for 55.94 seconds.

Processing rows:  24%|████████▉                             | 1224/5169 [1:11:04<1:21:49,  1.24s/it]

Rate limit reached. Sleeping for 56.29 seconds.

Processing rows:  24%|█████████                             | 1239/5169 [1:12:02<2:10:35,  1.99s/it]

Rate limit reached. Sleeping for 57.70 seconds.

Processing rows:  24%|█████████▏                            | 1258/5169 [1:13:03<1:41:47,  1.56s/it]

Rate limit reached. Sleeping for 57.34 seconds.

Processing rows:  25%|█████████▎                            | 1275/5169 [1:14:02<1:43:03,  1.59s/it]

Rate limit reached. Sleeping for 57.60 seconds.

Processing rows:  25%|█████████▍                            | 1292/5169 [1:15:03<1:39:28,  1.54s/it]

Rate limit reached. Sleeping for 57.54 seconds.

Processing rows:  25%|█████████▌                            | 1309/5169 [1:16:03<1:47:17,  1.67s/it]

Rate limit reached. Sleeping for 57.40 seconds.

Processing rows:  26%|█████████▋                            | 1326/5169 [1:17:03<1:35:54,  1.50s/it]

Rate limit reached. Sleeping for 56.59 seconds.

Processing rows:  26%|█████████▊                            | 1343/5169 [1:18:03<1:25:00,  1.33s/it]

Rate limit reached. Sleeping for 57.09 seconds.

Processing rows:  26%|█████████▉                            | 1360/5169 [1:19:03<1:26:12,  1.36s/it]

Rate limit reached. Sleeping for 57.07 seconds.

Processing rows:  27%|██████████                            | 1377/5169 [1:20:03<1:20:24,  1.27s/it]

Rate limit reached. Sleeping for 57.46 seconds.

Processing rows:  27%|██████████▏                           | 1394/5169 [1:21:03<1:16:50,  1.22s/it]

Rate limit reached. Sleeping for 56.73 seconds.

Processing rows:  27%|██████████▎                           | 1411/5169 [1:22:02<1:25:40,  1.37s/it]

Rate limit reached. Sleeping for 58.14 seconds.

Processing rows:  28%|██████████▍                           | 1428/5169 [1:23:03<1:29:47,  1.44s/it]

Rate limit reached. Sleeping for 56.90 seconds.

Processing rows:  28%|██████████▌                           | 1445/5169 [1:24:03<1:29:33,  1.44s/it]

Rate limit reached. Sleeping for 56.86 seconds.

Processing rows:  28%|██████████▋                           | 1462/5169 [1:25:03<1:20:50,  1.31s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  29%|██████████▊                           | 1479/5169 [1:26:03<1:24:25,  1.37s/it]

Rate limit reached. Sleeping for 57.18 seconds.

Processing rows:  29%|██████████▉                           | 1495/5169 [1:27:03<1:38:26,  1.61s/it]

Rate limit reached. Sleeping for 57.29 seconds.

Processing rows:  29%|███████████                           | 1513/5169 [1:28:02<1:34:10,  1.55s/it]

Rate limit reached. Sleeping for 57.69 seconds.

Processing rows:  30%|███████████▏                          | 1530/5169 [1:29:04<1:46:38,  1.76s/it]

Rate limit reached. Sleeping for 56.20 seconds.

Processing rows:  30%|███████████▎                          | 1547/5169 [1:30:05<1:22:29,  1.37s/it]

Rate limit reached. Sleeping for 55.39 seconds.

Processing rows:  30%|███████████▍                          | 1564/5169 [1:31:03<1:33:20,  1.55s/it]

Rate limit reached. Sleeping for 56.80 seconds.

Processing rows:  31%|███████████▌                          | 1580/5169 [1:32:03<1:33:43,  1.57s/it]

Rate limit reached. Sleeping for 57.33 seconds.

Processing rows:  31%|███████████▋                          | 1596/5169 [1:33:03<1:41:14,  1.70s/it]

Rate limit reached. Sleeping for 57.29 seconds.

Processing rows:  31%|███████████▊                          | 1613/5169 [1:34:02<1:55:22,  1.95s/it]

Rate limit reached. Sleeping for 57.99 seconds.

Processing rows:  32%|███████████▉                          | 1632/5169 [1:35:03<1:30:39,  1.54s/it]

Rate limit reached. Sleeping for 57.52 seconds.

Processing rows:  32%|████████████                          | 1648/5169 [1:36:03<1:30:46,  1.55s/it]

Rate limit reached. Sleeping for 57.41 seconds.

Processing rows:  32%|████████████▏                         | 1665/5169 [1:37:02<1:20:48,  1.38s/it]

Rate limit reached. Sleeping for 57.72 seconds.

Processing rows:  33%|████████████▎                         | 1683/5169 [1:38:03<1:34:49,  1.63s/it]

Rate limit reached. Sleeping for 57.16 seconds.

Processing rows:  33%|████████████▍                         | 1700/5169 [1:39:04<1:43:39,  1.79s/it]

Rate limit reached. Sleeping for 56.62 seconds.

Processing rows:  33%|████████████▌                         | 1716/5169 [1:40:03<2:00:03,  2.09s/it]

Rate limit reached. Sleeping for 57.20 seconds.

Processing rows:  34%|████████████▋                         | 1733/5169 [1:41:02<1:42:42,  1.79s/it]

Rate limit reached. Sleeping for 57.92 seconds.

Processing rows:  34%|████████████▊                         | 1751/5169 [1:42:02<1:12:15,  1.27s/it]

Rate limit reached. Sleeping for 57.98 seconds.

Processing rows:  34%|████████████▉                         | 1767/5169 [1:43:03<1:16:52,  1.36s/it]

Rate limit reached. Sleeping for 57.33 seconds.

Processing rows:  35%|█████████████                         | 1784/5169 [1:44:02<1:35:19,  1.69s/it]

Rate limit reached. Sleeping for 58.06 seconds.

Processing rows:  35%|█████████████▏                        | 1801/5169 [1:45:02<1:44:13,  1.86s/it]

Rate limit reached. Sleeping for 58.18 seconds.

Processing rows:  35%|█████████████▎                        | 1818/5169 [1:46:02<1:41:38,  1.82s/it]

Rate limit reached. Sleeping for 58.06 seconds.

Processing rows:  36%|█████████████▍                        | 1836/5169 [1:47:04<1:24:08,  1.51s/it]

Rate limit reached. Sleeping for 56.47 seconds.

Processing rows:  36%|█████████████▌                        | 1851/5169 [1:48:03<1:43:33,  1.87s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  36%|█████████████▋                        | 1869/5169 [1:49:03<1:21:38,  1.48s/it]

Rate limit reached. Sleeping for 57.70 seconds.

Processing rows:  37%|█████████████▊                        | 1887/5169 [1:50:03<1:31:05,  1.67s/it]

Rate limit reached. Sleeping for 57.11 seconds.

Processing rows:  37%|█████████████▉                        | 1904/5169 [1:51:04<1:14:19,  1.37s/it]

Rate limit reached. Sleeping for 56.58 seconds.

Processing rows:  37%|██████████████                        | 1921/5169 [1:52:03<1:12:03,  1.33s/it]

Rate limit reached. Sleeping for 57.68 seconds.

Processing rows:  37%|██████████████▏                       | 1937/5169 [1:53:02<1:33:49,  1.74s/it]

Rate limit reached. Sleeping for 57.97 seconds.

Processing rows:  38%|██████████████▎                       | 1954/5169 [1:54:03<1:40:07,  1.87s/it]

Rate limit reached. Sleeping for 57.51 seconds.

Processing rows:  38%|██████████████▍                       | 1972/5169 [1:55:03<1:15:22,  1.41s/it]

Rate limit reached. Sleeping for 57.53 seconds.

Processing rows:  38%|██████████████▌                       | 1989/5169 [1:56:03<1:08:10,  1.29s/it]

Rate limit reached. Sleeping for 57.24 seconds.

Processing rows:  39%|██████████████▋                       | 2006/5169 [1:57:04<1:15:56,  1.44s/it]

Rate limit reached. Sleeping for 56.57 seconds.

Processing rows:  39%|██████████████▊                       | 2023/5169 [1:58:03<1:11:19,  1.36s/it]

Rate limit reached. Sleeping for 57.44 seconds.

Processing rows:  39%|██████████████▉                       | 2040/5169 [1:59:03<1:21:57,  1.57s/it]

Rate limit reached. Sleeping for 57.74 seconds.

Processing rows:  40%|███████████████                       | 2056/5169 [2:00:02<1:25:03,  1.64s/it]

Rate limit reached. Sleeping for 57.92 seconds.

Processing rows:  40%|███████████████▏                      | 2074/5169 [2:01:03<1:16:06,  1.48s/it]

Rate limit reached. Sleeping for 57.34 seconds.

Processing rows:  40%|███████████████▎                      | 2091/5169 [2:02:03<1:03:17,  1.23s/it]

Rate limit reached. Sleeping for 57.48 seconds.

Processing rows:  41%|████████████████▎                       | 2108/5169 [2:03:03<58:56,  1.16s/it]

Rate limit reached. Sleeping for 57.76 seconds.

Processing rows:  41%|███████████████▌                      | 2125/5169 [2:04:03<1:21:55,  1.61s/it]

Rate limit reached. Sleeping for 57.67 seconds.

Processing rows:  41%|███████████████▋                      | 2142/5169 [2:05:02<1:02:44,  1.24s/it]

Rate limit reached. Sleeping for 58.06 seconds.

Processing rows:  42%|███████████████▊                      | 2159/5169 [2:06:03<1:11:29,  1.43s/it]

Rate limit reached. Sleeping for 57.64 seconds.

Processing rows:  42%|███████████████▉                      | 2176/5169 [2:07:03<1:18:44,  1.58s/it]

Rate limit reached. Sleeping for 57.64 seconds.

Processing rows:  42%|████████████████                      | 2193/5169 [2:08:03<1:24:14,  1.70s/it]

Rate limit reached. Sleeping for 57.23 seconds.

Processing rows:  43%|████████████████▏                     | 2210/5169 [2:09:03<1:22:34,  1.67s/it]

Rate limit reached. Sleeping for 57.76 seconds.

Processing rows:  43%|████████████████▎                     | 2226/5169 [2:10:03<1:33:42,  1.91s/it]

Rate limit reached. Sleeping for 57.79 seconds.

Processing rows:  43%|████████████████▍                     | 2244/5169 [2:11:03<1:14:27,  1.53s/it]

Rate limit reached. Sleeping for 57.88 seconds.

Processing rows:  44%|████████████████▌                     | 2261/5169 [2:12:03<1:25:11,  1.76s/it]

Rate limit reached. Sleeping for 57.77 seconds.

Processing rows:  44%|████████████████▋                     | 2276/5169 [2:13:03<1:39:19,  2.06s/it]

Rate limit reached. Sleeping for 57.86 seconds.

Processing rows:  44%|████████████████▊                     | 2295/5169 [2:14:03<1:00:56,  1.27s/it]

Rate limit reached. Sleeping for 57.92 seconds.

Processing rows:  45%|████████████████▉                     | 2309/5169 [2:15:02<1:41:18,  2.13s/it]

Rate limit reached. Sleeping for 58.13 seconds.

Processing rows:  45%|█████████████████                     | 2329/5169 [2:16:03<1:17:43,  1.64s/it]

Rate limit reached. Sleeping for 57.67 seconds.

Processing rows:  45%|█████████████████▏                    | 2346/5169 [2:17:03<1:03:21,  1.35s/it]

Rate limit reached. Sleeping for 57.10 seconds.

Processing rows:  46%|█████████████████▎                    | 2363/5169 [2:18:03<1:12:56,  1.56s/it]

Rate limit reached. Sleeping for 57.44 seconds.

Processing rows:  46%|█████████████████▍                    | 2380/5169 [2:19:03<1:15:07,  1.62s/it]

Rate limit reached. Sleeping for 57.81 seconds.

Processing rows:  46%|█████████████████▌                    | 2395/5169 [2:20:03<1:22:57,  1.79s/it]

Rate limit reached. Sleeping for 57.24 seconds.

Processing rows:  47%|█████████████████▋                    | 2412/5169 [2:21:02<1:34:14,  2.05s/it]

Rate limit reached. Sleeping for 58.24 seconds.

Processing rows:  47%|█████████████████▊                    | 2431/5169 [2:22:03<1:12:03,  1.58s/it]

Rate limit reached. Sleeping for 57.78 seconds.

Processing rows:  47%|█████████████████▉                    | 2448/5169 [2:23:03<1:09:07,  1.52s/it]

Rate limit reached. Sleeping for 57.52 seconds.

Processing rows:  48%|██████████████████                    | 2464/5169 [2:24:03<1:14:39,  1.66s/it]

Rate limit reached. Sleeping for 57.25 seconds.

Processing rows:  48%|██████████████████▏                   | 2481/5169 [2:25:03<1:05:12,  1.46s/it]

Rate limit reached. Sleeping for 57.38 seconds.

Processing rows:  48%|██████████████████▎                   | 2499/5169 [2:26:03<1:17:33,  1.74s/it]

Rate limit reached. Sleeping for 57.34 seconds.

Processing rows:  49%|██████████████████▍                   | 2515/5169 [2:27:03<1:08:20,  1.55s/it]

Rate limit reached. Sleeping for 57.69 seconds.

Processing rows:  49%|██████████████████▌                   | 2532/5169 [2:28:03<1:16:47,  1.75s/it]

Rate limit reached. Sleeping for 58.20 seconds.

Processing rows:  49%|███████████████████▋                    | 2550/5169 [2:29:03<56:56,  1.30s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  50%|██████████████████▊                   | 2567/5169 [2:30:04<1:09:17,  1.60s/it]

Rate limit reached. Sleeping for 56.58 seconds.

Processing rows:  50%|██████████████████▉                   | 2582/5169 [2:31:03<1:30:40,  2.10s/it]

Rate limit reached. Sleeping for 58.02 seconds.

Processing rows:  50%|███████████████████                   | 2601/5169 [2:32:03<1:00:39,  1.42s/it]

Rate limit reached. Sleeping for 57.35 seconds.

Processing rows:  51%|███████████████████▏                  | 2617/5169 [2:33:03<1:15:22,  1.77s/it]

Rate limit reached. Sleeping for 57.79 seconds.

Processing rows:  51%|███████████████████▎                  | 2635/5169 [2:34:03<1:13:34,  1.74s/it]

Rate limit reached. Sleeping for 57.26 seconds.

Processing rows:  51%|███████████████████▍                  | 2652/5169 [2:35:03<1:13:59,  1.76s/it]

Rate limit reached. Sleeping for 57.56 seconds.

Processing rows:  52%|███████████████████▌                  | 2668/5169 [2:36:03<1:16:18,  1.83s/it]

Rate limit reached. Sleeping for 57.82 seconds.

Processing rows:  52%|███████████████████▋                  | 2685/5169 [2:37:03<1:13:03,  1.76s/it]

Rate limit reached. Sleeping for 58.03 seconds.

Processing rows:  52%|███████████████████▊                  | 2700/5169 [2:38:03<1:26:50,  2.11s/it]

Rate limit reached. Sleeping for 58.13 seconds.

Processing rows:  53%|█████████████████████                   | 2720/5169 [2:39:03<53:16,  1.31s/it]

Rate limit reached. Sleeping for 57.35 seconds.

Processing rows:  53%|████████████████████                  | 2736/5169 [2:40:02<1:19:50,  1.97s/it]

Rate limit reached. Sleeping for 58.32 seconds.

Processing rows:  53%|████████████████████▏                 | 2754/5169 [2:41:03<1:05:04,  1.62s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  54%|█████████████████████▍                  | 2771/5169 [2:42:04<54:23,  1.36s/it]

Rate limit reached. Sleeping for 56.84 seconds.

Processing rows:  54%|█████████████████████▌                  | 2788/5169 [2:43:03<56:08,  1.41s/it]

Rate limit reached. Sleeping for 57.51 seconds.

Processing rows:  54%|████████████████████▌                 | 2805/5169 [2:44:04<1:02:50,  1.60s/it]

Rate limit reached. Sleeping for 57.20 seconds.

Processing rows:  55%|█████████████████████▊                  | 2822/5169 [2:45:03<53:28,  1.37s/it]

Rate limit reached. Sleeping for 57.58 seconds.

Processing rows:  55%|████████████████████▊                 | 2838/5169 [2:46:02<1:18:37,  2.02s/it]

Rate limit reached. Sleeping for 58.37 seconds.

Processing rows:  55%|████████████████████▉                 | 2856/5169 [2:47:03<1:08:13,  1.77s/it]

Rate limit reached. Sleeping for 57.45 seconds.

Processing rows:  56%|██████████████████████▏                 | 2873/5169 [2:48:04<52:41,  1.38s/it]

Rate limit reached. Sleeping for 57.03 seconds.

Processing rows:  56%|█████████████████████▏                | 2889/5169 [2:49:03<1:10:49,  1.86s/it]

Rate limit reached. Sleeping for 57.51 seconds.

Processing rows:  56%|█████████████████████▎                | 2906/5169 [2:50:03<1:08:40,  1.82s/it]

Rate limit reached. Sleeping for 57.77 seconds.

Processing rows:  57%|██████████████████████▋                 | 2924/5169 [2:51:04<52:13,  1.40s/it]

Rate limit reached. Sleeping for 57.17 seconds.

Processing rows:  57%|█████████████████████▌                | 2940/5169 [2:52:03<1:01:19,  1.65s/it]

Rate limit reached. Sleeping for 57.52 seconds.

Processing rows:  57%|█████████████████████▋                | 2958/5169 [2:53:03<1:02:40,  1.70s/it]

Rate limit reached. Sleeping for 58.07 seconds.

Processing rows:  58%|█████████████████████▊                | 2975/5169 [2:54:04<1:02:32,  1.71s/it]

Rate limit reached. Sleeping for 57.36 seconds.

Processing rows:  58%|███████████████████████▏                | 2991/5169 [2:55:04<52:41,  1.45s/it]

Rate limit reached. Sleeping for 56.74 seconds.

Processing rows:  58%|███████████████████████▎                | 3009/5169 [2:56:03<47:56,  1.33s/it]

Rate limit reached. Sleeping for 57.72 seconds.

Processing rows:  59%|██████████████████████▏               | 3025/5169 [2:57:03<1:14:32,  2.09s/it]

Rate limit reached. Sleeping for 58.05 seconds.

Processing rows:  59%|██████████████████████▎               | 3042/5169 [2:58:03<1:05:48,  1.86s/it]

Rate limit reached. Sleeping for 57.83 seconds.

Processing rows:  59%|███████████████████████▋                | 3060/5169 [2:59:04<49:01,  1.39s/it]

Rate limit reached. Sleeping for 57.48 seconds.

Processing rows:  60%|███████████████████████▊                | 3077/5169 [3:00:04<49:00,  1.41s/it]

Rate limit reached. Sleeping for 57.26 seconds.

Processing rows:  60%|██████████████████████▋               | 3093/5169 [3:01:04<1:05:51,  1.90s/it]

Rate limit reached. Sleeping for 57.20 seconds.

Processing rows:  60%|████████████████████████                | 3111/5169 [3:02:04<50:02,  1.46s/it]

Rate limit reached. Sleeping for 57.32 seconds.

Processing rows:  61%|████████████████████████▏               | 3128/5169 [3:03:04<53:33,  1.57s/it]

Rate limit reached. Sleeping for 56.85 seconds.

Processing rows:  61%|████████████████████████▎               | 3145/5169 [3:04:05<48:21,  1.43s/it]

Rate limit reached. Sleeping for 56.37 seconds.

Processing rows:  61%|████████████████████████▍               | 3161/5169 [3:05:03<51:47,  1.55s/it]

Rate limit reached. Sleeping for 57.60 seconds.

Processing rows:  62%|████████████████████████▌               | 3179/5169 [3:06:04<48:19,  1.46s/it]

Rate limit reached. Sleeping for 57.38 seconds.

Processing rows:  62%|████████████████████████▋               | 3196/5169 [3:07:04<44:02,  1.34s/it]

Rate limit reached. Sleeping for 56.62 seconds.

Processing rows:  62%|████████████████████████▊               | 3213/5169 [3:08:04<41:00,  1.26s/it]

Rate limit reached. Sleeping for 57.44 seconds.

Processing rows:  62%|████████████████████████▉               | 3230/5169 [3:09:05<52:54,  1.64s/it]

Rate limit reached. Sleeping for 56.48 seconds.

Processing rows:  63%|█████████████████████████▏              | 3247/5169 [3:10:04<43:21,  1.35s/it]

Rate limit reached. Sleeping for 56.71 seconds.

Processing rows:  63%|█████████████████████████▎              | 3264/5169 [3:11:04<45:53,  1.45s/it]

Rate limit reached. Sleeping for 56.75 seconds.

Processing rows:  63%|█████████████████████████▍              | 3281/5169 [3:12:04<39:41,  1.26s/it]

Rate limit reached. Sleeping for 56.72 seconds.

Processing rows:  64%|█████████████████████████▌              | 3298/5169 [3:13:04<40:14,  1.29s/it]

Rate limit reached. Sleeping for 56.68 seconds.

Processing rows:  64%|█████████████████████████▋              | 3314/5169 [3:14:06<54:44,  1.77s/it]

Rate limit reached. Sleeping for 55.32 seconds.

Processing rows:  64%|█████████████████████████▊              | 3330/5169 [3:15:04<58:33,  1.91s/it]

Rate limit reached. Sleeping for 57.50 seconds.

Processing rows:  65%|█████████████████████████▉              | 3349/5169 [3:16:04<53:30,  1.76s/it]

Rate limit reached. Sleeping for 56.89 seconds.

Processing rows:  65%|██████████████████████████              | 3366/5169 [3:17:04<48:08,  1.60s/it]

Rate limit reached. Sleeping for 57.19 seconds.

Processing rows:  65%|██████████████████████████▏             | 3382/5169 [3:18:03<54:18,  1.82s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  66%|██████████████████████████▎             | 3400/5169 [3:19:05<36:59,  1.25s/it]

Rate limit reached. Sleeping for 56.56 seconds.

Processing rows:  66%|██████████████████████████▍             | 3416/5169 [3:20:04<46:17,  1.58s/it]

Rate limit reached. Sleeping for 57.01 seconds.

Processing rows:  66%|██████████████████████████▌             | 3434/5169 [3:21:04<30:40,  1.06s/it]

Rate limit reached. Sleeping for 57.16 seconds.

Processing rows:  67%|██████████████████████████▋             | 3451/5169 [3:22:04<45:43,  1.60s/it]

Rate limit reached. Sleeping for 56.95 seconds.

Processing rows:  67%|██████████████████████████▊             | 3468/5169 [3:23:05<48:06,  1.70s/it]

Rate limit reached. Sleeping for 56.63 seconds.

Processing rows:  67%|██████████████████████████▉             | 3485/5169 [3:24:04<37:30,  1.34s/it]

Rate limit reached. Sleeping for 56.81 seconds.

Processing rows:  68%|███████████████████████████             | 3502/5169 [3:25:05<38:00,  1.37s/it]

Rate limit reached. Sleeping for 56.15 seconds.

Processing rows:  68%|███████████████████████████▏            | 3517/5169 [3:26:04<55:10,  2.00s/it]

Rate limit reached. Sleeping for 57.69 seconds.

Processing rows:  68%|███████████████████████████▎            | 3535/5169 [3:27:04<48:57,  1.80s/it]

Rate limit reached. Sleeping for 57.43 seconds.

Processing rows:  69%|███████████████████████████▍            | 3552/5169 [3:28:04<49:12,  1.83s/it]

Rate limit reached. Sleeping for 57.24 seconds.

Processing rows:  69%|███████████████████████████▋            | 3570/5169 [3:29:04<48:28,  1.82s/it]

Rate limit reached. Sleeping for 57.00 seconds.

Processing rows:  69%|███████████████████████████▊            | 3587/5169 [3:30:04<38:52,  1.47s/it]

Rate limit reached. Sleeping for 56.94 seconds.

Processing rows:  70%|███████████████████████████▉            | 3604/5169 [3:31:03<41:23,  1.59s/it]

Rate limit reached. Sleeping for 57.85 seconds.

Processing rows:  70%|████████████████████████████            | 3620/5169 [3:32:05<48:25,  1.88s/it]

Rate limit reached. Sleeping for 56.71 seconds.

Processing rows:  70%|████████████████████████████▏           | 3638/5169 [3:33:05<34:01,  1.33s/it]

Rate limit reached. Sleeping for 56.45 seconds.

Processing rows:  71%|████████████████████████████▎           | 3655/5169 [3:34:03<32:31,  1.29s/it]

Rate limit reached. Sleeping for 57.89 seconds.

Processing rows:  71%|████████████████████████████▍           | 3672/5169 [3:35:05<36:20,  1.46s/it]

Rate limit reached. Sleeping for 56.68 seconds.

Processing rows:  71%|████████████████████████████▌           | 3688/5169 [3:36:03<35:53,  1.45s/it]

Rate limit reached. Sleeping for 57.94 seconds.

Processing rows:  72%|████████████████████████████▋           | 3705/5169 [3:37:05<39:54,  1.64s/it]

Rate limit reached. Sleeping for 56.32 seconds.

Processing rows:  72%|███████████████████████████▎          | 3718/5169 [3:38:04<1:07:58,  2.81s/it]

Error: Invalid JSON format after cleaning

Processing rows:  72%|████████████████████████████▊           | 3723/5169 [3:38:05<33:25,  1.39s/it]

Rate limit reached. Sleeping for 56.18 seconds.

Processing rows:  72%|████████████████████████████▉           | 3740/5169 [3:39:04<31:59,  1.34s/it]

Rate limit reached. Sleeping for 57.63 seconds.

Processing rows:  73%|█████████████████████████████           | 3757/5169 [3:40:05<39:02,  1.66s/it]

Rate limit reached. Sleeping for 56.76 seconds.

Processing rows:  73%|█████████████████████████████▏          | 3774/5169 [3:41:04<30:41,  1.32s/it]

Rate limit reached. Sleeping for 57.21 seconds.

Processing rows:  73%|█████████████████████████████▎          | 3791/5169 [3:42:04<38:57,  1.70s/it]

Rate limit reached. Sleeping for 57.40 seconds.

Processing rows:  74%|█████████████████████████████▍          | 3807/5169 [3:43:04<35:00,  1.54s/it]

Rate limit reached. Sleeping for 57.08 seconds.

Processing rows:  74%|█████████████████████████████▌          | 3825/5169 [3:44:04<31:04,  1.39s/it]

Rate limit reached. Sleeping for 57.70 seconds.

Processing rows:  74%|█████████████████████████████▋          | 3842/5169 [3:45:04<41:33,  1.88s/it]

Rate limit reached. Sleeping for 57.17 seconds.

Processing rows:  75%|█████████████████████████████▊          | 3859/5169 [3:46:05<30:24,  1.39s/it]

Rate limit reached. Sleeping for 56.52 seconds.

Processing rows:  75%|█████████████████████████████▉          | 3876/5169 [3:47:04<32:10,  1.49s/it]

Rate limit reached. Sleeping for 57.10 seconds.

Processing rows:  75%|██████████████████████████████          | 3892/5169 [3:48:06<39:53,  1.87s/it]

Rate limit reached. Sleeping for 55.65 seconds.

Processing rows:  76%|██████████████████████████████▎         | 3910/5169 [3:49:04<27:04,  1.29s/it]

Rate limit reached. Sleeping for 57.05 seconds.

Processing rows:  76%|██████████████████████████████▍         | 3927/5169 [3:50:05<27:43,  1.34s/it]

Rate limit reached. Sleeping for 56.95 seconds.

Processing rows:  76%|██████████████████████████████▌         | 3943/5169 [3:51:04<32:11,  1.58s/it]

Rate limit reached. Sleeping for 57.18 seconds.

Processing rows:  77%|██████████████████████████████▋         | 3961/5169 [3:52:05<23:48,  1.18s/it]

Rate limit reached. Sleeping for 56.44 seconds.

Processing rows:  77%|██████████████████████████████▊         | 3978/5169 [3:53:06<25:28,  1.28s/it]

Rate limit reached. Sleeping for 55.94 seconds.

Processing rows:  77%|██████████████████████████████▉         | 3995/5169 [3:54:05<26:44,  1.37s/it]

Rate limit reached. Sleeping for 56.71 seconds.

Processing rows:  78%|███████████████████████████████         | 4011/5169 [3:55:04<36:34,  1.89s/it]

Rate limit reached. Sleeping for 57.15 seconds.

Processing rows:  78%|███████████████████████████████▏        | 4028/5169 [3:56:04<32:34,  1.71s/it]

Rate limit reached. Sleeping for 57.24 seconds.

Processing rows:  78%|███████████████████████████████▎        | 4045/5169 [3:57:04<34:10,  1.82s/it]

Rate limit reached. Sleeping for 57.57 seconds.

Processing rows:  79%|███████████████████████████████▍        | 4063/5169 [3:58:04<23:27,  1.27s/it]

Rate limit reached. Sleeping for 57.82 seconds.

Processing rows:  79%|███████████████████████████████▌        | 4080/5169 [3:59:04<25:25,  1.40s/it]

Rate limit reached. Sleeping for 57.69 seconds.

Processing rows:  79%|███████████████████████████████▋        | 4097/5169 [4:00:04<22:32,  1.26s/it]

Rate limit reached. Sleeping for 57.10 seconds.

Processing rows:  80%|███████████████████████████████▊        | 4114/5169 [4:01:05<19:42,  1.12s/it]

Rate limit reached. Sleeping for 56.42 seconds.

Processing rows:  80%|███████████████████████████████▉        | 4131/5169 [4:02:06<24:45,  1.43s/it]

Rate limit reached. Sleeping for 56.02 seconds.

Processing rows:  80%|████████████████████████████████        | 4148/5169 [4:03:05<23:01,  1.35s/it]

Rate limit reached. Sleeping for 56.44 seconds.

Processing rows:  81%|████████████████████████████████▏       | 4165/5169 [4:04:05<18:42,  1.12s/it]

Rate limit reached. Sleeping for 57.06 seconds.

Processing rows:  81%|████████████████████████████████▎       | 4182/5169 [4:05:04<21:51,  1.33s/it]

Rate limit reached. Sleeping for 57.25 seconds.

Processing rows:  81%|████████████████████████████████▍       | 4199/5169 [4:06:05<22:12,  1.37s/it]

Rate limit reached. Sleeping for 56.43 seconds.

Processing rows:  82%|████████████████████████████████▌       | 4215/5169 [4:07:04<25:24,  1.60s/it]

Rate limit reached. Sleeping for 57.31 seconds.

Processing rows:  82%|████████████████████████████████▊       | 4233/5169 [4:08:06<24:03,  1.54s/it]

Rate limit reached. Sleeping for 56.06 seconds.

Processing rows:  82%|████████████████████████████████▉       | 4250/5169 [4:09:05<22:56,  1.50s/it]

Rate limit reached. Sleeping for 56.98 seconds.

Processing rows:  83%|█████████████████████████████████       | 4266/5169 [4:10:05<25:11,  1.67s/it]

Rate limit reached. Sleeping for 56.64 seconds.

Processing rows:  83%|█████████████████████████████████▏      | 4282/5169 [4:11:04<25:35,  1.73s/it]

Rate limit reached. Sleeping for 57.64 seconds.

Processing rows:  83%|█████████████████████████████████▎      | 4301/5169 [4:12:05<18:34,  1.28s/it]

Rate limit reached. Sleeping for 56.89 seconds.

Processing rows:  84%|█████████████████████████████████▍      | 4318/5169 [4:13:04<17:50,  1.26s/it]

Rate limit reached. Sleeping for 57.31 seconds.

Processing rows:  84%|█████████████████████████████████▌      | 4335/5169 [4:14:05<19:07,  1.38s/it]

Rate limit reached. Sleeping for 57.01 seconds.

Processing rows:  84%|█████████████████████████████████▋      | 4352/5169 [4:15:05<19:29,  1.43s/it]

Rate limit reached. Sleeping for 56.82 seconds.

Processing rows:  85%|█████████████████████████████████▊      | 4369/5169 [4:16:05<18:13,  1.37s/it]

Rate limit reached. Sleeping for 56.95 seconds.

Processing rows:  85%|█████████████████████████████████▉      | 4386/5169 [4:17:06<21:10,  1.62s/it]

Rate limit reached. Sleeping for 55.45 seconds.

Processing rows:  85%|██████████████████████████████████      | 4403/5169 [4:18:05<19:53,  1.56s/it]

Rate limit reached. Sleeping for 56.24 seconds.

Processing rows:  85%|██████████████████████████████████▏     | 4419/5169 [4:19:05<22:19,  1.79s/it]

Rate limit reached. Sleeping for 56.56 seconds.

Processing rows:  86%|██████████████████████████████████▎     | 4437/5169 [4:20:06<17:56,  1.47s/it]

Rate limit reached. Sleeping for 56.24 seconds.

Processing rows:  86%|██████████████████████████████████▍     | 4454/5169 [4:21:04<14:04,  1.18s/it]

Rate limit reached. Sleeping for 57.56 seconds.

Processing rows:  86%|██████████████████████████████████▌     | 4471/5169 [4:22:05<19:31,  1.68s/it]

Rate limit reached. Sleeping for 56.94 seconds.

Processing rows:  87%|██████████████████████████████████▋     | 4488/5169 [4:23:05<15:45,  1.39s/it]

Rate limit reached. Sleeping for 56.74 seconds.

Processing rows:  87%|██████████████████████████████████▊     | 4505/5169 [4:24:05<13:08,  1.19s/it]

Rate limit reached. Sleeping for 56.87 seconds.

Processing rows:  87%|██████████████████████████████████▉     | 4522/5169 [4:25:06<16:55,  1.57s/it]

Rate limit reached. Sleeping for 55.65 seconds.

Processing rows:  88%|███████████████████████████████████     | 4539/5169 [4:26:04<16:30,  1.57s/it]

Rate limit reached. Sleeping for 57.44 seconds.

Processing rows:  88%|███████████████████████████████████▏    | 4555/5169 [4:27:04<18:31,  1.81s/it]

Rate limit reached. Sleeping for 58.12 seconds.

Processing rows:  88%|███████████████████████████████████▍    | 4573/5169 [4:28:05<13:23,  1.35s/it]

Rate limit reached. Sleeping for 57.12 seconds.

Processing rows:  89%|███████████████████████████████████▌    | 4590/5169 [4:29:04<12:17,  1.27s/it]

Rate limit reached. Sleeping for 57.39 seconds.

Processing rows:  89%|███████████████████████████████████▋    | 4607/5169 [4:30:05<12:34,  1.34s/it]

Rate limit reached. Sleeping for 57.05 seconds.

Processing rows:  89%|███████████████████████████████████▊    | 4624/5169 [4:31:05<12:15,  1.35s/it]

Rate limit reached. Sleeping for 56.96 seconds.

Processing rows:  90%|███████████████████████████████████▉    | 4641/5169 [4:32:04<10:54,  1.24s/it]

Rate limit reached. Sleeping for 57.43 seconds.

Processing rows:  90%|████████████████████████████████████    | 4658/5169 [4:33:05<11:21,  1.33s/it]

Rate limit reached. Sleeping for 56.82 seconds.

Processing rows:  90%|████████████████████████████████████▏   | 4675/5169 [4:34:07<10:14,  1.24s/it]

Rate limit reached. Sleeping for 55.29 seconds.

Processing rows:  91%|████████████████████████████████████▎   | 4692/5169 [4:35:05<09:43,  1.22s/it]

Rate limit reached. Sleeping for 56.88 seconds.

Processing rows:  91%|████████████████████████████████████▍   | 4708/5169 [4:36:04<12:24,  1.61s/it]

Rate limit reached. Sleeping for 57.63 seconds.

Processing rows:  91%|████████████████████████████████████▌   | 4725/5169 [4:37:04<11:29,  1.55s/it]

Rate limit reached. Sleeping for 57.40 seconds.

Processing rows:  92%|████████████████████████████████████▋   | 4743/5169 [4:38:05<08:42,  1.23s/it]

Rate limit reached. Sleeping for 57.07 seconds.

Processing rows:  92%|████████████████████████████████████▊   | 4760/5169 [4:39:04<10:23,  1.52s/it]

Rate limit reached. Sleeping for 57.63 seconds.

Processing rows:  92%|████████████████████████████████████▉   | 4777/5169 [4:40:05<08:12,  1.26s/it]

Rate limit reached. Sleeping for 57.37 seconds.

Processing rows:  93%|█████████████████████████████████████   | 4794/5169 [4:41:05<08:18,  1.33s/it]

Rate limit reached. Sleeping for 56.55 seconds.

Processing rows:  93%|█████████████████████████████████████▏  | 4811/5169 [4:42:05<06:30,  1.09s/it]

Rate limit reached. Sleeping for 56.63 seconds.

Processing rows:  93%|█████████████████████████████████████▎  | 4828/5169 [4:43:04<07:21,  1.29s/it]

Rate limit reached. Sleeping for 57.56 seconds.

Processing rows:  94%|█████████████████████████████████████▍  | 4845/5169 [4:44:06<07:41,  1.42s/it]

Rate limit reached. Sleeping for 55.79 seconds.

Processing rows:  94%|█████████████████████████████████████▌  | 4862/5169 [4:45:04<07:08,  1.40s/it]

Rate limit reached. Sleeping for 57.46 seconds.

Processing rows:  94%|█████████████████████████████████████▊  | 4879/5169 [4:46:07<07:58,  1.65s/it]

Rate limit reached. Sleeping for 55.27 seconds.

Processing rows:  95%|█████████████████████████████████████▉  | 4896/5169 [4:47:05<06:11,  1.36s/it]

Rate limit reached. Sleeping for 57.15 seconds.

Processing rows:  95%|██████████████████████████████████████  | 4911/5169 [4:48:04<08:57,  2.08s/it]

Rate limit reached. Sleeping for 57.90 seconds.

Processing rows:  95%|██████████████████████████████████████▏ | 4930/5169 [4:49:05<05:49,  1.46s/it]

Rate limit reached. Sleeping for 56.51 seconds.

Processing rows:  96%|██████████████████████████████████████▎ | 4947/5169 [4:50:04<04:43,  1.28s/it]

Rate limit reached. Sleeping for 58.01 seconds.

Processing rows:  96%|██████████████████████████████████████▍ | 4964/5169 [4:51:04<04:54,  1.43s/it]

Rate limit reached. Sleeping for 57.85 seconds.

Processing rows:  96%|██████████████████████████████████████▌ | 4981/5169 [4:52:04<05:02,  1.61s/it]

Rate limit reached. Sleeping for 58.03 seconds.

Processing rows:  97%|██████████████████████████████████████▋ | 4997/5169 [4:53:04<05:21,  1.87s/it]

Rate limit reached. Sleeping for 57.98 seconds.

Processing rows:  97%|██████████████████████████████████████▊ | 5013/5169 [4:54:04<05:24,  2.08s/it]

Rate limit reached. Sleeping for 58.27 seconds.

Processing rows:  97%|██████████████████████████████████████▉ | 5030/5169 [4:55:04<04:42,  2.03s/it]

Rate limit reached. Sleeping for 57.57 seconds.

Processing rows:  98%|███████████████████████████████████████ | 5049/5169 [4:56:04<02:54,  1.45s/it]

Rate limit reached. Sleeping for 57.78 seconds.

Processing rows:  98%|███████████████████████████████████████▏| 5066/5169 [4:57:05<02:22,  1.38s/it]

Rate limit reached. Sleeping for 57.57 seconds.

Processing rows:  98%|███████████████████████████████████████▎| 5083/5169 [4:58:04<02:42,  1.88s/it]

Rate limit reached. Sleeping for 58.06 seconds.

Processing rows:  99%|███████████████████████████████████████▍| 5100/5169 [4:59:05<01:44,  1.52s/it]

Rate limit reached. Sleeping for 57.00 seconds.

Processing rows:  99%|███████████████████████████████████████▌| 5117/5169 [5:00:04<01:24,  1.63s/it]

Rate limit reached. Sleeping for 58.11 seconds.

Processing rows:  99%|███████████████████████████████████████▋| 5133/5169 [5:01:05<01:00,  1.67s/it]

Rate limit reached. Sleeping for 57.29 seconds.

Processing rows: 100%|███████████████████████████████████████▊| 5150/5169 [5:02:04<00:28,  1.52s/it]

Rate limit reached. Sleeping for 57.74 seconds.

Processing rows: 100%|████████████████████████████████████████| 5169/5169 [5:03:07<00:00,  3.52s/it]

In [17]:
# Réactiver la mise en veille à la fin
ctypes.windll.kernel32.SetThreadExecutionState(0x80000000)  # ES_CONTINUOUS

-2147483648